DECLARE 
    
  /*CREATE THE EXCEPCION*/
  NEGATIVE_VALUE EXCEPTION;
  
  /*VARIABLE TO THROW THE EXCEPTION*/
  NUMBER_VALUE NUMBER;
  
  BEGIN
    /*THE VARIABLE WILL  HAVE A NEGATIVE VALUE*/
    NUMBER_VALUE := -1;
    
    /*VALIDATE THE VALUE IF IS NEGATIVE NUMBER*/
    IF NUMBER_VALUE < 0 THEN
      
      /*IF THE CONDITION IS TRUE, THROW THE PERSONAL EXCEPCTION*/
      RAISE NEGATIVE_VALUE;
      
      END IF;
      
    EXCEPTION
      /*CATCH THE EXCEPTION */
      WHEN NEGATIVE_VALUE THEN 
            
       /*PRINT A MESSAGE INSIDE OF THE EXCEPTION*/
      SYS.DBMS_OUTPUT.PUT_LINE('THE VALUE CAN NOT BE NEGATIVE');


END;