DECLARE       
  /*DECLARE THE VARIABLE THAT IT WILL SAVE THE CURRENT DATE*/ 
  CURR_DATE DATE;
  
      /*CREATE A FUNCTION TO GET THE CURRENT DATE WITH A ERROR IN THE QUERY*/
      FUNCTION FN_CURRENT_DATE RETURN DATE
      
        IS
          CURR_DATE DATE;
          
          BEGIN 
          
            SELECT SYSDATE INTO CURR_DATE
            FROM DUAL
            WHERE 1=2;/*THAT IS THE ERROR*/
            RETURN CURR_DATE;
            
            EXCEPTION 
            /*EXCEPTION THAT NOT WORK IN THIS CODE BLOCK*/
            WHEN ZERO_DIVIDE THEN
               SYS.DBMS_OUTPUT.PUT_LINE('EXCEPTION ZERO DIVIDE HAS BENN CATCH');
         END; 
         
  /*IN THIS BLOCK WILL BE CATCH THE EXCEPTION*/
  BEGIN 
  
    /*VARIABLE TO SAVE THE RESULT OF THE FUNCTION*/
    CURR_DATE := FN_CURRENT_DATE();
    SYS.DBMS_OUTPUT.PUT_LINE('THE CURRENT DATE IS '||TO_CHAR(CURR_DATE, 'DD/MM/YYYY'));
    
    EXCEPTION
    
        /*CREATE THE RIGTH EXCEPTION*/
      WHEN NO_DATA_FOUND THEN
        SYS.DBMS_OUTPUT.PUT_LINE('EXCEPTION NO DATA FOUND HAS BEEN CATCH IN THE MAIN BLOCK');
 
  END;